version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: eu.gcr.io/wire-bot/tracking-bot
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bot
      - DB_USER=bot
      - DB_PASSWORD=bot
    depends_on:
      - db

  db:
    image: postgres:13.1
    # just for local development
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=bot
    ports:
      - 5432:5432
    volumes:
      - tracking-bot-db:/var/lib/postgresql/data/

volumes:
  tracking-bot-db:
